import {
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowUp,
  BadgeCheck,
  BadgeX,
  Ban,
  Bell,
  BookOpen,
  Building2,
  Calendar,
  CalendarClock,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  Clock,
  ClockAlert,
  Eye,
  FilePen,
  Filter,
  History,
  Home,
  Info,
  LayoutDashboard,
  Link2,
  Loader,
  Menu,
  MessageSquare,
  MoreHorizontal,
  PackageCheck,
  Paperclip,
  Pause,
  Plus,
  Replace,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  SlidersHorizontal,
  User,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";

/** Lucide-based icon system (outline, consistent stroke). */
export const icons = {
  archive: Archive,
  "alert-triangle": AlertTriangle,
  "arrow-down": ArrowDown,
  "arrow-up": ArrowUp,
  "badge-check": BadgeCheck,
  "badge-x": BadgeX,
  ban: Ban,
  bell: Bell,
  "book-open": BookOpen,
  "building-2": Building2,
  calendar: Calendar,
  "calendar-clock": CalendarClock,
  "chart-column": ChartColumn,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle-check": CircleCheck,
  clock: Clock,
  "clock-alert": ClockAlert,
  eye: Eye,
  "file-pen": FilePen,
  filter: Filter,
  history: History,
  home: Home,
  info: Info,
  "layout-dashboard": LayoutDashboard,
  "link-2": Link2,
  loader: Loader,
  menu: Menu,
  "message-square": MessageSquare,
  "more-horizontal": MoreHorizontal,
  "package-check": PackageCheck,
  paperclip: Paperclip,
  pause: Pause,
  plus: Plus,
  replace: Replace,
  search: Search,
  settings: Settings,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shield-x": ShieldX,
  "sliders-horizontal": SlidersHorizontal,
  user: User,
  users: Users,
  x: X,
} as const;

export type IconName = keyof typeof icons;

export function getIcon(name: IconName): LucideIcon {
  return icons[name];
}
